// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RoomInteriorGenerator")>]
[<assembly: AssemblyProductAttribute("RoomInteriorGenerator")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-11-13T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","a51c1e11892e6e55febc38e837694e0b45f2476a")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RoomInteriorGenerator"
    let [<Literal>] AssemblyProduct = "RoomInteriorGenerator"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-11-13T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "a51c1e11892e6e55febc38e837694e0b45f2476a"
